# Generated by Django 3.2.12 on 2023-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户唯一凭证')),
                ('lastLoginTime', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
            ],
        ),
    ]
